[package]
name = "magayon-furniture"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"
build = "build.rs"

[lib]
name = "magayon_furniture_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bcrypt = "0.12"
tokio = { version = "1", features = ["full"] }
tokio-postgres = "0.7.13"
axum = "0.8.3"
tower = "0.4"
dotenvy = "0.15"
sqlx = { version = "0.7", features = ["postgres", "runtime-tokio-native-tls", "chrono", "rust_decimal"] } # <--- QUITADO "decimal"
chrono = { version = "0.4", features = ["serde"] }
rust_decimal = { version = "1", features = ["serde"] } # <--- SOLO este es necesario para Decimal
dotenvy_macro = "0.15"
num-traits = "0.2.19"
